### ISSUE TITLE
Error loading Windows Phone Seed Project (Package creator fails)

### ISSUE THREAD

**Issue by jose-e-rodriguez** [auth0/docs#136]
Windows phone Seed Project Link sends to a localhost:3000 address
(https://localhost:3000/docs/Auth0.WindowsPhone/master/create-package?path=examples/WindowsPhoneSilverlight&type=none&clientId=08t4pch5E6TFfiOA4i6wGmOsSS27P9ly). 

When changed localhost:3000 to the path for "https://auth0.com/docs/" like the rest of the Seed projects

(https://auth0.com/docs/Auth0.WindowsPhone/master/create-package?path=examples/WindowsPhoneSilverlight&type=none&clientId=08t4pch5E6TFfiOA4i6wGmOsSS27P9ly) the page loads with the following errors:

TypeError: Cannot call method 'bind' of undefined
at Packer.create (/usr/local/lib/node_modules/auth0-package-creator/node_modules/configurated-sample-generator/packer.js:43:40)
at /usr/local/lib/node_modules/auth0-package-creator/server.js:50:10
at Layer.handle as handle_request (/usr/local/lib/node_modules/auth0-package-creator/node_modules/express/lib/router/layer.js:82:5)
at next (/usr/local/lib/node_modules/auth0-package-creator/node_modules/express/lib/router/route.js:110:13)
at Route.dispatch (/usr/local/lib/node_modules/auth0-package-creator/node_modules/express/lib/router/route.js:91:3)
at Layer.handle as handle_request (/usr/local/lib/node_modules/auth0-package-creator/node_modules/express/lib/router/layer.js:82:5)
at /usr/local/lib/node_modules/auth0-package-creator/node_modules/express/lib/router/index.js:267:22
at param (/usr/local/lib/node_modules/auth0-package-creator/node_modules/express/lib/router/index.js:340:14)
at param (/usr/local/lib/node_modules/auth0-package-creator/node_modules/express/lib/router/index.js:356:14)
at param (/usr/local/lib/node_modules/auth0-package-creator/node_modules/express/lib/router/index.js:356:14)
at Function.proto.process_params (/usr/local/lib/node_modules/auth0-package-creator/node_modules/express/lib/router/index.js:400:3)
at next (/usr/local/lib/node_modules/auth0-package-creator/node_modules/express/lib/router/index.js:261:10)
at /usr/local/lib/node_modules/auth0-package-creator/node_modules/express-validator/lib/express_validator.js:250:12
at Layer.handle as handle_request (/usr/local/lib/node_modules/auth0-package-creator/node_modules/express/lib/router/layer.js:82:5)
at trim_prefix (/usr/local/lib/node_modules/auth0-package-creator/node_modules/express/lib/router/index.js:302:13)
at /usr/local/lib/node_modules/auth0-package-creator/node_modules/express/lib/router/index.js:270:7

**Comment by ntotten** [comment]
Fixed
