### ISSUE TITLE
Requests for invalid docs return too much info

### ISSUE THREAD

**Issue by yvonnewilson** [auth0/docs#3523]
Making a request for an invalid docs URL returns more info than necessary.  Should just return the equivalent of "not found" without all the additional info.

As reported in ticket:
https://auth0.zendesk.com/agent/tickets/20200

this is probably not a big issue but wanted to let you guys know that there's a very minor information disclosure happening when someone requests invalid document url:

Example URL:

https://auth0.com/docs/abc

response consists following:

&lt;p data-reactid="537"&gt;No document found at /docs/abc&lt;/p&gt;&lt;pre style="padding:30px;overflow-x:auto;" data-reactid="538"&gt;Error: No document found at /docs/abc 
at /usr/local/lib/node_modules/auth0-docs/client/services/DocumentService.server.js:12:21 
at new Promise (/usr/local/lib/node_modules/auth0-docs/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:201:7) 
at Object.DocumentService.load (/usr/local/lib/node_modules/auth0-docs/client/services/DocumentService.server.js:7:3) 
at loadDocument (/usr/local/lib/node_modules/auth0-docs/client/action/loadDocument.js:46:4) 
at Immediate._onImmediate (/usr/local/lib/node_modules/auth0-docs/node_modules/fluxible/utils/callAction.js:20:34) 
at processImmediate [as _immediateCallback] (timers.js:383:17)&lt;/pre&gt;

**Comment by mpaktiti** [comment]
Hello @yvonnewilson I'm not sure if that got fixed in the meanwhile, but when I follow this link I cannot see the info you're posting. I'll close this but if you check and the issue persists let me know and I can reopen it at the `auth0-docs` repo.
